name: CI Pipeline

# Définition des déclencheurs
on:
  push:
    branches:
      - SP-101-CI-CD/feat-creation-workflow
  pull_request:
    branches:
      - SP-101-CI-CD/feat-creation-workflow

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    # Stratégie pour tester différentes versions de Node.js (facultatif)
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    # Vérification du dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configuration de la version de Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # Installation des dépendances
    - name: Install dependencies
      run: npm install

    # Exécution des tests
    - name: Run tests
      run: npm run test
