name: CI Pipeline

on:
  push:
    branches:
      - SP-101-CI-CD/feat-creation-workflow
  pull_request:
    branches:
      - SP-101-CI-CD/feat-creation-workflow

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # Se déplacer dans le répertoire 'client'
    - name: Change directory to /client
      working-directory: ./client

    # Installation des dépendances dans le répertoire 'client'
    - name: Install dependencies
      run: npm install
      working-directory: ./client

    # Exécution des tests dans le répertoire 'client'
    - name: Run tests
      run: npm test
      working-directory: ./client
